In [2]:
#using LinearAlgebra
import numpy as np
from scipy.linalg import null_space

## Exercícios da aula 2
### 1. Mostre que o espaço nulo de $AB$ contém o espaço nulo de $B$.

Seja $\vec{x}$ uma solução para $B\vec{x} = 0$, é possível afirmar que $AB\vec{x} = A(B\vec{x}) = A  \vec{0} = 0$

### 2. Qual a relação entre o espaço nulo de $C$ e os espaços nulos de $A$ e $B$, se $C = \begin{bmatrix} A\\ B \end{bmatrix}$?

$dim \space {\mathcal N}(C)  \leq  dim \space {\mathcal N}(A), dim \space {\mathcal N}(B)$




### 3. Mostre que ${\mathcal N}(A^T A) = {\mathcal N}(A)$.

Seja $\vec{x}$ pertencente a ${\mathcal N}(A)$:

$A\vec{x}=0 \space ; A^TA\vec{x} = 0$  - conclui-se que o espaço nulo de $A$ está contido no espaço nulo de $A^TA$

Seja $\vec{x}$ pertencente a ${\mathcal N}(A^TA)$:

$A^TA\vec{x} = 0 \space ; \vec{x^T}A^TA\vec{x} = 0 → (A\vec{x})^T(A\vec{x}) = 0$

Tomando dessa última expressão $Ax =y$ temos $y^Ty=0$ que só é possivel quando $y=0$ - logo o espaço nulo de $A^TA$ está contido no espaço nulo de $A$.
Para que ${\mathcal N}(A^TA) \subset {\mathcal N}(A)$ e ${\mathcal N}(A) \subset {\mathcal N}(A^TA)$, $\space {\mathcal N}(A^TA) = {\mathcal N}(A)$

### 4. Se espaço coluna de $A$ = espaço linha de $A$, e ${\mathcal N}(A) = {\mathcal N}(A^T)$, podemos concluir que $A$ é simétrica? Explique sua resposta.

Não, porque sendo $A$ uma matriz $n\space x\space n$, de posto completo, o espaço coluna de $A = $ espaço linha de $A = $ ${\mathcal R}^n$ e ${\mathcal N}(A) = {\mathcal N}(A^T) = 0$ e existem matrizes que cumprem essas condições e não são simétricas.

Exemplo: $\begin{bmatrix} 1 & 2 & 1 \\ 1 & 1 & 1 \\ 3 & 4 & 2\end{bmatrix}$

### 5. Se ${\mathcal N}(A) = \{{\bf{0}}\}$, quais vetores pertencem ao espaço nulo  de $B = [A \;\; A \;\; A]$?

Adotando as dimensões adequadas (cada elemento representa n vetores coluna), são necessários vetores que gerem combinações lineares de A:
$span( \begin{bmatrix} 1\\0\\-1 \end{bmatrix}, \begin{bmatrix} 0\\1\\-1 \end{bmatrix})$

### 6. Considere o grafo obtido da seguinte maneira: os quatro cantos de um quadrado, mais o ponto central são os nós, conectados entre si (as arestas), gerando um grafo com cinco nós e oito arestas. Escreva a *matriz de incidência* $A$ desse grafo, calcule o posto de $A$ e encontre um vetor $x \in {\mathcal N}(A)$ e quatro vetores linearmente independentes $y_i \in {\mathcal N}(A^T)$, $i = 1, \ldots , 4$.

$A = \begin{bmatrix} -1 & 1 & 0 & 0 & 0\\ 0 & -1 & 1 & 0 & 0\\ 0& 0 & -1 & 1 & 0 \\ 1 & 0 & 0 & -1 & 0\\ -1 & 0 & 0 & 0 & 1 \\ 0 & -1 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0 & -1 \\ 0 & 0 & 0 & 1 & -1 \end{bmatrix}$

$x \in {\mathcal N}(A)$: $x = \begin{bmatrix} 1\\1\\1\\1\\1 \end{bmatrix}$

In [8]:
# Define your matrix A
A = np.array([[-1, 0, 0, 1, -1, 0, 0, 0],
              [1, -1, 0, 0, 0, -1, 0, 0],
              [0, 1, -1, 0, 0, 0, 1, 0],
              [0, 0, 1, -1, 0, 0, 0, 1],
              [0, 0, 0, 0, 1, 1, -1, -1]])

# Find the null space of A
null_space_A = null_space(A)

# Get four linearly independent solutions from the null space
four_solutions = null_space_A[:, :4]

# Print the solutions
print("Four Linearly Independent Solutions of Ax = 0:")
print(four_solutions)
#As 4 soluções distintas são as colunas da matriz exibida ao rodar o código

Four Linearly Independent Solutions of Ax = 0:
[[-0.64025704  0.20508344  0.09861651  0.07037867]
 [-0.48960833 -0.41016687 -0.19723301 -0.14075734]
 [-0.26363525 -0.2718246   0.45192744 -0.34501609]
 [-0.30129743 -0.28281102  0.38785794  0.38140617]
 [ 0.33895961 -0.48789446  0.28924144  0.3110275 ]
 [-0.15064872  0.61525031  0.29584952  0.21113602]
 [ 0.22597307  0.13834227  0.64916045 -0.20425874]
 [-0.03766218 -0.01098642 -0.06406949  0.72642225]]


### 7. Sejam $S,T$ subespaços de ${\mathbb R}^{10}$, com $\dim (S) = 2, \dim(T) = 7$. Quais as dimensões possíveis de (i) $S \cap T$, (ii) $S + T$ (soma direta dos subespaçõs), (iii) $S^{\perp} := \{ v \in {\mathbb R}^{10}: v^Ts = 0, \forall s \in S\}$. (complemento ortogonal de $S$)?

#### Definição: A *soma direta de dois subespaços* $S,T$ de um espaço vetorial é definida como $\{ s + t: s \in S, t \in T\}$.

i) 0, 1 e 2

ii) 0 até 9

iii)0 até 8